In [26]:
using LinearAlgebrΩ

In [27]:
A=[12.0 -51 4
   6   167 -68
   -4 24 -41]


3×3 Matrix{Float64}:
 12.0  -51.0    4.0
  6.0  167.0  -68.0
 -4.0   24.0  -41.0

In [28]:
sign(-3)

-1

In [29]:
function normalizar(z)
    return z/norm(z)
end

normalizar (generic function with 1 method)

In [30]:
function criaVetorW(x, m)
    w = zeros(m)               # Cria um vetor de zeros de tamanho m
    w[1] = norm(x)             # Define o primeiro elemento como a norma do vetor x
    return w                   # Retorna o vetor w
end


criaVetorW (generic function with 1 method)

In [23]:
function householder(A)
        m,n=size(A)
        for k=1:n
            x=A[k:m,k] #seleciona a coluna de A que começa na linha k
            v=x-norm(x)*[1;zeros(n-k)] # vetor coluna 
            v=normalizar(v)
            for j=1:n
                A[j:m,j:n]=A[j:m,j:n]-(2*v*v')*A[j:m,j:n]
            end
            #b[k:m]=b[k:m]-2*v[k]*v[k]'*b[k:m]'
        end
        return A #b
end

householder (generic function with 1 method)

In [25]:
householder(A)

LoadError: DimensionMismatch: A has dimensions (3,3) but B has dimensions (2,2)

In [ ]:
det(A'*A)

0.0

In [ ]:
B=[12 24.0 -62
   4  14  104
   -3 2  -53]
householder(B)

3×3 Matrix{Float64}:
 13.0          26.0  -13.0
 -8.88178e-16  10.0   20.0
  4.44089e-16   0.0  130.0

In [ ]:
A'*A

2×2 Matrix{Int64}:
 10000000000000001  -9999999999999999
 -9999999999999999  10000000000000001

In [ ]:
A=randn(30,20)
householder(A)

30×20 Matrix{Float64}:
  5.50777       0.744791      0.990954     …   0.291942      0.311616
 -2.77556e-17  -4.95042      -0.09779         -1.79174      -1.0506
 -5.55112e-17   1.11022e-16   5.09117          0.506945      0.0415043
 -5.55112e-17  -2.77556e-17  -1.11022e-16     -1.14691      -0.149181
  2.22045e-16   0.0          -5.55112e-17      1.76522       0.191632
  4.44089e-16   2.77556e-17  -5.55112e-17  …  -1.1997        1.57722
  4.44089e-16   4.44089e-16  -5.55112e-17     -2.05505      -0.32691
 -2.22045e-16   0.0          -5.55112e-17     -0.669403     -0.417447
  5.55112e-17  -2.22045e-16   4.44089e-16      0.395111     -0.123114
 -4.44089e-16   3.46945e-18  -5.55112e-17      0.690918      0.0111639
  1.11022e-16   1.11022e-16  -2.22045e-16  …   1.14805      -0.09878
 -2.22045e-16   2.22045e-16  -4.44089e-16      1.50998      -0.246409
 -4.44089e-16   5.55112e-17  -1.11022e-16      1.96181      -0.455687
  ⋮                                        ⋱                
 -5.55112

In [ ]:
k=2
m,n=size(A)
x=A[2:3,2]
v=norm(x)*[1;zeros(m-k)]+x
v=normalizar(v)
A[k:m,k:n]=A[k:m,k:n]-2*v*v'*A[k:m,k:n]

2×2 Matrix{Float64}:
 -175.0  70.0
    0.0  35.0